# Pages configuration
name = "emojis"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-09-03"
compatibility_flags = ["nodejs_compat"]

# Environment variables (these will need to be set in Cloudflare dashboard)
# [vars]
# DEFAULT_PROVIDER = "gemini"
# GEMINI_MODEL = "gemini-2.5-flash-lite"
# OPENAI_MODEL = "gpt-4o-mini"

# Secrets (set via: wrangler secret put GEMINI_API_KEY)
# GEMINI_API_KEY
# GOOGLE_API_KEY
# OPENAI_API_KEY
