export type EmojiDictionary = {
  // key is lowercased word or phrase
  [key: string]: string;
};

// A small, expressive dictionary. Add more as desired.
export const EMOJI_DICTIONARY: EmojiDictionary = {
  // Phrases
  'good morning': '🌞✨',
  'good afternoon': '🌤️',
  'good evening': '🌇',
  'good night': '🌙✨',
  'i love you': '❤️',
  'i love': '❤️',
  'i like': '👍',
  'miss you': '🥺💭',
  'see you': '👋',
  'see you soon': '👋⏳',
  'thank you': '🙏',
  'thanks a lot': '🙏✨',
  'you are welcome': '🙌',
  'good job': '👏',
  'well done': '👏',
  'happy birthday': '🎂🎉',
  'congratulations': '🎉',
  'happy anniversary': '💞🎉',
  'good luck': '🍀',
  'have fun': '🎉',
  'take care': '🤗',
  'i am sorry': '🙏😞',
  'no worries': '👌',
  'excuse me': '🙏',
  'bless you': '🤧🙏',
  'good morning sunshine': '🌞✨',
  'love you so much': '❤️🥰',
  'i am hungry': '🤤',
  'i am thirsty': '🥤',
  'on my way': '🏃‍♂️💨',
  'be right back': '↩️',
  'see you later': '👋⏰',
  'good to go': '✅',
  'need coffee': '☕️',
  'time to sleep': '😴',
  'time to eat': '🍽️',
  'time to party': '🎉',
  'let’s party': '🎉',
  'let us party': '🎉',
  'cheers to you': '🥂',
  'good vibes': '✨',
  'i am tired': '😪',
  'just kidding': '😉',
  'for real': '🤔✅',
  'no way': '🙅‍♂️',
  'hurry up': '⏩',
  'calm down': '🧘',
  'hold on': '✋',
  'call me': '📞',
  'text me': '💬',
  'let’s go': '🏁',
  'way to go': '👏',
  'i am home': '🏠',
  'at work': '💼',
  'at the gym': '🏋️',
  'on vacation': '🏖️',
  'road trip': '🚗🛣️',
  'good game': '🎮👍',

  // Common words: greetings
  hello: '👋',
  hi: '👋',
  hey: '👋',
  welcome: '🙏',
  bye: '👋',
  goodbye: '👋',
  cheers: '🥂',

  // Acknowledgement / reactions
  love: '❤️',
  like: '👍',
  liked: '👍',
  dislike: '👎',
  yes: '✅',
  yeah: '✅',
  yup: '✅',
  no: '❌',
  nope: '❌',
  ok: '👌',
  okay: '👌',
  cool: '😎',
  nice: '✨',
  perfect: '✅',
  correct: '✅',
  wrong: '❌',
  maybe: '🤔',
  wait: '⏳',
  soon: '⏳',
  later: '⏰',
  now: '⚡️',

  // Emotions
  lol: '😂',
  lmao: '🤣',
  rofl: '🤣',
  haha: '😄',
  happy: '😊',
  joy: '😂',
  sad: '😢',
  cry: '😢',
  crying: '😭',
  hurt: '🤕',
  angry: '😠',
  mad: '😠',
  upset: '😞',
  shocked: '😱',
  surprised: '😲',
  wow: '🤩',
  excited: '🤩',
  bored: '🥱',
  tired: '😪',
  sleepy: '😴',
  confused: '😕',
  thinking: '🤔',
  nervous: '😬',
  coolness: '😎',
  kiss: '😘',
  hug: '🤗',
  hope: '🤞',
  lucky: '🍀',
  shockedface: '😱',

  // Activities / verbs
  read: '📖',
  write: '✍️',
  draw: '✏️',
  paint: '🎨',
  code: '💻',
  program: '💻',
  build: '🏗️',
  cook: '🍳',
  eat: '🍽️',
  drink: '🥤',
  sleep: '😴',
  run: '🏃‍♂️',
  walk: '🚶',
  drive: '🚗',
  fly: '✈️',
  swim: '🏊',
  dance: '💃',
  sing: '🎤',
  play: '🎮',
  watch: '👀',
  listen: '🎧',
  learn: '📚',
  study: '📚',
  travel: '🌍✈️',
  celebrate: '🎉',
  party: '🎉',
  meditate: '🧘',
  shop: '🛍️',
  clean: '🧹',
  wash: '🧼',
  workout: '🏋️',
  exercise: '🏃‍♂️',
  relax: '😌',
  think: '🤔',
  focus: '🎯',
  help: '🆘',
  fix: '🛠️',
  save: '💾',
  send: '📤',
  receive: '📥',

  // Food & drink
  pizza: '🍕',
  burger: '🍔',
  fries: '🍟',
  taco: '🌮',
  burrito: '🌯',
  sushi: '🍣',
  ramen: '🍜',
  noodles: '🍝',
  pasta: '🍝',
  salad: '🥗',
  steak: '🥩',
  chicken: '🍗',
  fish: '🐟',
  egg: '🥚',
  eggs: '🥚',
  cheese: '🧀',
  bread: '🍞',
  cake: '🍰',
  cupcake: '🧁',
  cookie: '🍪',
  chocolate: '🍫',
  icecream: '🍨',
  ice: '🧊',
  candy: '🍬',
  apple: '🍎',
  banana: '🍌',
  orange: '🍊',
  mango: '🥭',
  grape: '🍇',
  watermelon: '🍉',
  strawberry: '🍓',
  lemon: '🍋',
  peach: '🍑',
  avocado: '🥑',
  corn: '🌽',
  carrot: '🥕',
  potato: '🥔',
  tomato: '🍅',
  pepper: '🌶️',
  mushroom: '🍄',
  coffee: '☕️',
  tea: '🍵',
  boba: '🧋',
  milk: '🥛',
  juice: '🧃',
  water: '💧',
  beer: '🍺',
  wine: '🍷',
  cocktail: '🍹',

  // Weather & nature
  sun: '☀️',
  sunny: '☀️',
  moon: '🌙',
  star: '⭐️',
  rainbow: '🌈',
  cloud: '☁️',
  rain: '🌧️',
  thunder: '⛈️',
  lightning: '⚡️',
  storm: '🌩️',
  snow: '❄️',
  windy: '💨',
  wind: '💨',
  fog: '🌫️',
  fire: '🔥',
  lit: '🔥',
  tree: '🌳',
  flower: '🌸',
  rose: '🌹',
  tulip: '🌷',
  blossom: '🌼',
  leaf: '🍃',
  ocean: '🌊',
  wave: '🌊',
  mountain: '⛰️',
  volcano: '🌋',
  desert: '🏜️',

  // Animals
  cat: '🐱',
  kitten: '🐱',
  dog: '🐶',
  puppy: '🐶',
  mouse: '🐭',
  rabbit: '🐰',
  panda: '🐼',
  bear: '🐻',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  monkey: '🐵',
  pig: '🐷',
  chickenanimal: '🐔',
  cow: '🐮',
  horse: '🐴',
  sheep: '🐑',
  frog: '🐸',
  bird: '🐦',
  penguin: '🐧',
  duck: '🦆',
  eagle: '🦅',
  owl: '🦉',
  fishanimal: '🐟',
  whale: '🐳',
  dolphin: '🐬',
  shark: '🦈',
  octopus: '🐙',
  crab: '🦀',
  butterfly: '🦋',
  bee: '🐝',
  bug: '🐞',
  snail: '🐌',

  // Travel & places
  car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  train: '🚆',
  subway: '🚇',
  tram: '🚊',
  airplane: '✈️',
  flight: '✈️',
  ship: '🚢',
  boat: '⛵️',
  bicycle: '🚲',
  scooter: '🛵',
  rocket: '🚀',
  hotel: '🏨',
  house: '🏠',
  home: '🏠',
  office: '🏢',
  school: '🏫',
  hospital: '🏥',
  bank: '🏦',
  park: '🏞️',
  beach: '🏖️',
  island: '🏝️',
  stadium: '🏟️',
  store: '🏬',
  shopplace: '🏬',

  // Tech & work
  phone: '📱',
  call: '📞',
  message: '💬',
  email: '✉️',
  inbox: '📥',
  outbox: '📤',
  laptop: '💻',
  computer: '💻',
  keyboard: '⌨️',
  mousepad: '🖱️',
  battery: '🔋',
  camera: '📷',
  video: '🎬',
  picture: '🖼️',
  tv: '📺',
  radio: '📻',
  wifi: '📶',
  internet: '🌐',
  link: '🔗',
  lock: '🔒',
  unlock: '🔓',
  bugfix: '🪲',
  idea: '💡',
  note: '📝',
  calendar: '📅',
  clock: '🕒',
  time: '⏰',
  alarm: '⏰',
  map: '🗺️',
  location: '📍',
  pin: '📍',
  search: '🔎',
  settings: '⚙️',
  tool: '🛠️',
  hammer: '🔨',
  wrench: '🔧',

  // Sports & games
  soccer: '⚽️',
  football: '🏈',
  basketball: '🏀',
  baseball: '⚾️',
  tennis: '🎾',
  golf: '⛳️',
  boxing: '🥊',
  running: '🏃‍♂️',
  hiking: '🥾',
  skiing: '🎿',
  snowboard: '🏂',
  yoga: '🧘',
  game: '🎮',
  dice: '🎲',
  trophy: '🏆',

  // Celebrations & symbols
  gift: '🎁',
  present: '🎁',
  partyhat: '🥳',
  fireworks: '🎆',
  sparkles: '✨',
  starstruck: '🤩',
  heart: '❤️',
  hearts: '💞',
  brokenheart: '💔',
  flame: '🔥',
  snowflake: '❄️',
  umbrella: '☂️',
  recycle: '♻️',
  warning: '⚠️',
  stop: '🛑',
  check: '✅',
  cross: '❌',
  plus: '➕',
  minus: '➖',
  up: '⬆️',
  down: '⬇️',
  left: '⬅️',
  right: '➡️',

  // Time of day
  morning: '🌅',
  noon: '🏙️',
  evening: '🌇',
  night: '🌃',

  // Misc useful words
  work: '💼',
  money: '💰',
  banknote: '💵',
  sale: '🏷️',
  giftcard: '🎟️',
  book: '📕',
  paper: '📄',
  package: '📦',
  shopping: '🛍️',
  cart: '🛒',
  ticket: '🎫',
  art: '🎨',
  music: '🎵',
  song: '🎵',
  guitar: '🎸',
  piano: '🎹',
  movie: '🎬',
  sleepyn: '😴',
  prayer: '🙏',
  thanks: '🙏',
  please: '🙏',
};

function escapeRegExp(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function sortKeysByWordLengthDesc(keys: string[]) {
  return [...keys].sort((a, b) => {
    const wa = a.trim().split(/\s+/).length;
    const wb = b.trim().split(/\s+/).length;
    if (wa !== wb) return wb - wa;
    return b.length - a.length;
  });
}

// Translate text: replace phrases first, then individual words.
export function translateToEmojis(input: string, dict: EmojiDictionary = EMOJI_DICTIONARY) {
  if (!input.trim()) return '';

  // 1) Replace multi-word phrases with their emoji equivalents.
  const phraseKeys = sortKeysByWordLengthDesc(
    Object.keys(dict).filter((k) => k.includes(' '))
  );

  let result = input;
  for (const key of phraseKeys) {
    const emoji = dict[key];
    const pattern = new RegExp(`\\b${escapeRegExp(key)}\\b`, 'gi');
    result = result.replace(pattern, emoji);
  }

  // 2) Replace single words while preserving punctuation.
  const tokens = result.split(/(\s+)/); // keep spaces

  const mapped = tokens.map((token) => {
    // Skip if token already contains emoji characters
    if (/\p{Extended_Pictographic}/u.test(token)) return token;

    // Extract leading/trailing punctuation around a central word
    const m = token.match(/^([^\p{L}\p{N}]*)((?:[\p{L}\p{N}][\p{L}\p{N}\-']*)?)([^\p{L}\p{N}]*)$/u);
    if (!m) return token; // space or non-word token
    const [, lead, core, tail] = m;
    if (!core) return token;

    const lower = core.toLowerCase();
    const emoji = dict[lower];
    return emoji ? `${lead}${emoji}${tail}` : token;
  });

  // 3) Collapse multiple adjacent emojis/spaces nicely
  const joined = mapped.join('');
  return joined.replace(/\s{2,}/g, ' ').trim();
}

export type HistoryItem = {
  id: string;
  input: string;
  output: string;
  timestamp: number;
};
